Repository AbdelRahmanRahal/GradeA, pull requests merged in 2024-12, with the labels that each got.

#27 User registration is now functional
  react/src/pages/register.jsx
  react/src/supabase.js
  supabase/.gitignore
Labels: enhancement

#32 Created a working basic dashboard
  react/src/App.jsx
  react/src/pages/dashboard.jsx
  react/src/pages/login.jsx
  react/src/pages/register.jsx
Labels: technical task

#33 Designed GradeA logo
  logo/logo.ai
  logo/logo.png
  logo/logo.psd
  logo/logo.svg
Labels: technical task

#44 Admin Dashboard
  react/src/App.jsx
  react/src/pages/admin-dashboard/admin-dashboard.jsx
  react/src/pages/admin-dashboard/components/AdminSidebar.jsx
  react/src/pages/admin-dashboard/components/CoursesSection.jsx
  react/src/pages/admin-dashboard/components/DataTable.jsx
  react/src/pages/admin-dashboard/components/ProfessorsSection.jsx
  react/src/pages/admin-dashboard/components/SearchBar.jsx
  react/src/pages/admin-dashboard/components/StudentsSection.jsx
  react/src/pages/dashboard/dashboard.jsx
Labels: technical task

#43 Create react-build.yml
  .github/workflows/react-build.yml
Labels: Test

#47 Faster dashboard, better dashboard.
  react/package.json
  react/src/pages/dashboard/dashboard.jsx
  react/src/pages/login/login.jsx
Labels: enhancement

#49 Create backend_check.yml
  .github/workflows/backend_check.yml
Labels: Test
